### ISSUE TITLE
Trailing whitespace displayed during animations

### ISSUE THREAD

**Issue by mcauley-penney** [Eandrju/cellular-automaton.nvim#1]
When the user has `set list` and has a character set for trailing white space, those characters will be used to display spaces in the animation. See below.

The solution I found was simply to place  `vim.api.nvim_win_set_option(window_id, "list", false)` in ui.open_window(). It's just one line, so idk if you want a PR for it.

Edit: the animation will also display listchars.eol at the end of the line, so it isn't only trailing spaces.

![whitespace](https://user-images.githubusercontent.com/59481467/204428072-322f9b01-7c1e-4897-86e0-caf4dea9475b.gif)

**Comment by Eandrju** [comment]
Oh thanks! No need for PR I'll push the fix later today. Thanks for spotting and debugging the issue
