### ISSUE TITLE
game_of_life has issues with code folding turned on

### ISSUE THREAD

**Issue by felixniemeyer** [Eandrju/cellular-automaton.nvim#14]
I use `set fdm=indent` in my config, which automatically folds indented lines. 
When executing `CellularAutomaton game_of_life` some lines are folded and unfolded each frame which results in a very untidy animation. 

Not sure if there is a fix for that, just want to contribute to this fun project.

**Comment by Eandrju** [comment]
Hey, folding and wrapping isn't supported as for now (it's mentioned in the readme). I just didn't have patience to tackle that. You are welcome to fix it if you want :)
