### ISSUE TITLE
no syntax highlighting for nvim in alacritty

### ISSUE THREAD

**Issue by Dowwie** [Eandrju/cellular-automaton.nvim#16]
when I apply either cellular automaton effect within nvim v0.8.2 using alacritty terminal, and tmux, within macos, all syntax highlighting is lost

**Comment by WuerfelDev** [comment]
Can't confirm. I have a similar setup with alacritty 0.11.0, nvim 0.8.2, tmux 3.3a, macOS 13.1

Do you use a custom color scheme? Maybe your problem is related to it?

**Comment by Eandrju** [comment]
Do you have treesitter plugin enabled?

**Comment by Dowwie** [comment]
I have treesitter installed via Plug and also TSInstall'd for the language I tested with (rust)

**Comment by Eandrju** [comment]
Could you try to update the plugin with latest changes? I've added some additional checks, that should raise an error if something is wrong.

**Comment by Dowwie** [comment]
I ran `:PlugUpdate` and then applied the plugin over rust code.  Still, no syntax highlighting.

**Comment by Eandrju** [comment]
Strange as I use the same configuration - tmux/alacritty/macos. Could you share the config files, I will try to reproduce it

**Comment by dinko-pehar** [comment]
Just found this thread.

I'm on similar path as @Dowwie . With `nix` package manager enabled on MacOS, I have tested this on various terminal and can confirm it always loses colorscheme.

Here is some info that may be useful to you:

- cellular-automation.nvim -> Latest commit (679943b8e1e5ef79aaeeaf4b00782c52eb4e928f)
- kitty -> 0.26.2
- allacrity -> 0.11.0
- Darwin 22.2.0, macOS 13.1

```nvim --version
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by _nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/w4yaqdag8bmx23nbzv5jc9j39dixlj75-neovim-unwrapped-0.8.2/share/nvim
"
```

**Comment by dinko-pehar** [comment]
I found solution to my problem.

I installed wanted Tree sitter plugins as before, but also there is some option `:TSToogle highlight` and the highlight started to appear.  I'm not familiar with TreeSitter, thought the installation of plugins were enough. Will take some time to understand everything about treesitter.

Thank you for the plugin btw 🚀 .

**Comment by Nacho114** [comment]
> I found solution to my problem.
> 
> I installed wanted Tree sitter plugins as before, but also there is some option `:TSToogle highlight` and the highlight started to appear. I'm not familiar with TreeSitter, thought the installation of plugins were enough. Will take some time to understand everything about treesitter.
> 
> Thank you for the plugin btw 🚀 .

Worked for me as well! Plus, I was finally able to use TreeSitter, I had the plugin but it was not active 😂 -- Since I have coc as well I already had partial highlighting.

**Comment by Eandrju** [comment]
:TSToogle highlight to the rescue it appears 👍
