### ISSUE TITLE
Plugin erroneously reporting 'Nested animations are forbidden'

### ISSUE THREAD

**Issue by taigrr** [Eandrju/cellular-automaton.nvim#3]
When trying to stop and restart the animation, the state machine thinks it's still running and refuses to rerun.

Usage: 
1. Run :CellularAutomaton game_of_life
1. quit (:q)
1. Run :CellularAutomaton game_of_life
1. Error message prints: 
Error executing Lua callback: ...llular-automaton.nvim/lua/cellular-automaton/manager.lua:33: Nested animations are forbidden

**Comment by Eandrju** [comment]
Ha I missed that. I confirm that I can reproduce it. I'll fix it soon, but for now you can quit the animation simply by typing 'q' without ':'

**Comment by Eandrju** [comment]
Forget to mention issue in commit, but this is now fixed. [here](https://github.com/Eandrju/cellular-automaton.nvim/blob/05d427e4788d0f09a3831037a92aa915411d64c6/lua/cellular-automaton/manager.lua#L57)
