### ISSUE TITLE
no colours in animations

### ISSUE THREAD

**Issue by backwardspy** [Eandrju/cellular-automaton.nvim#7]
hi, thanks for the super fun plugin!

the animations work fine in my setup, except when i start it all the highlights are lost and the cells just go white.

do you know what (kinds of) plugins might break the highlights on this one?

my config is here: https://github.com/backwardspy/dotfiles/tree/main/dot_config/nvim

**Comment by Eandrju** [comment]
hey, thanks. You don't have [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) installed :)

**Comment by backwardspy** [comment]
oh! well spotted, i had completely forgotten it wasn't in this config. thank you :)

**Comment by FormalSnake** [comment]
Even with treesitter it doesnt work, I have syntax highlighting and the colors are lost.

**Comment by FormalSnake** [comment]
This is my config btw https://github.com/FormalSnake/neovim

**Comment by FormalSnake** [comment]
@Eandrju

**Comment by Eandrju** [comment]
Try running  `:TSToggle highlight` and then triggering the animation

**Comment by FormalSnake** [comment]
Then it works, is there a workaround for this or should I make the shortcut toggle it and then run the animation?

**Comment by Eandrju** [comment]
Then it means you are not using treesitter for highlights. Just downloading it isn't enough. Read the manual for that plugin how to properly enable it.
